### ISSUE TITLE
Handover to R is slow

### ISSUE THREAD

**Issue by BerriJ** [zdebruine/RcppClock#1]
Hi,

let me say that I love RcppClock and I use it frequently.
However, recently I discovered performance issues and it turned out that RcppClock itself caused those issues. Considers this simple .cpp file:
```

// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::depends(RcppProgress)]]
// [[Rcpp::depends(RcppClock)]]
// [[Rcpp::plugins("cpp11")]]

#include <RcppArmadillo.h>
#include <progress.hpp>
#include <RcppClock.h>
#include <thread>

// [[Rcpp::export]]
int test()
{

    int X = 50;
    int Y = 50;
    int Z = 50;

    Progress prog(X * Y * Z);
    Rcpp::Clock clock;
    arma::wall_clock timer;

    for (unsigned int x = 0; x < X; x++)
    {
        for (unsigned int y = 0; y < Y; y++)
        {
            for (unsigned int z = 0; z < Z; z++)
            {
                clock.tick("Z action");
                arma::vec tmp(100, arma::fill::randu);
                clock.tock("Z action");
                prog.increment();
            }
        }
    }

    timer.tic();
    clock.stop("times");
    double n = timer.toc();
    arma::cout << "number of seconds: " << n << arma::endl;

    return 0;
}
```

RcppArmadillo, RcppClock, and RcppProgress are needed. Then this can be easily sourced using `Rcpp::sourceCpp("test.cpp")`

Now consider the following R code:
```
[R] test()                                                                           
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
number of seconds: 86.5003
[1] 0
```

The progressbar fills up extremely quick. However, it takes 86 seconds for `clock.stop("times");` to finish. How is that?
We can see that `times`'s footprint is not tiny indeed:
```
[R] sz <- object.size(times)                                                         

[R] print(sz, units = "MB")                                                          
1.9 Mb
```

However, 86 Seconds seems a bit hefty even if we have 1.2MB of data which has to be processed in some way.

Thank you so much.
BerriJ

**Comment by zdebruine** [comment]
Hi BerriJ,

Thanks for raising this issue.  You're right, `.stop()` is unduly slow for large numbers of data points.  

Just for the record, your test is generating 50 * 50 * 50 = 125000 points, so if each point were 8 bytes you're looking at 1 Mb just for the raw durations vector.

After running RcppClock, the results are sent to "R" using the following code embodied in the `.stop()` method:

```
void stop(std::string var_name) {
      for (unsigned int i = 0; i < tick_names.size(); ++i) {
        for (unsigned int j = 0; j < tock_names.size(); ++j) {
          if (tick_names[i] == tock_names[j]) {
            timers.push_back(duration(tock_times[j] - tick_times[i]));
            tickers.push_back(tick_names[i]);
            tock_times.erase(tock_times.begin() + j);
            tock_names.erase(tock_names.begin() + j);
            break;
          }
        }
      }
      // create R global environment variable
}
```

The bottleneck here is extensive memory reallocation in the `push_back` and `erase` operations.  Because RcppClock does not assume that each "tick" is immediately followed by its corresponding "tock" (there could be other "ticks" and/or "tocks" in between) it is necessary to map each "tick" to its immediately following "tock".  One way to do this better would be to align the "tock" vector to the "tick" vector, but this is a bit tricky because a simple swap sort won't do.

Why bother with overlapping time points?  Sometimes it's useful to time parent and nested processes together.  The major rationale for this, however, was to introduce OpenMP support, but so far I haven't gotten to this.

It might also be possible to introduce another clock class that uses `tick(std::string)` and `tock()` such that each `tock()` corresponds to the immediately preceding `tick()`. 

You're welcome to submit a PR anytime, it's a very small header file and pretty intuitive :)  I still want to switch out `std::high_resolution_clock` for `std::system_clock` per our previous correspondence.

Best,
Zach

**Comment by BerriJ** [comment]
Thank you for your reply. I'll add this Issue to my to-do but I can't promise anything at the moment.

On the other regard: 
> still want to switch out std::high_resolution_clock for std::system_clock

Do you think this comes without drawbacks?

**Comment by BerriJ** [comment]
I'm playing around with `std::map` and it looks promising. We should be able to get rid of those 2 nested loops and replace them with some non-nested loops. Consider this:

```
#include <RcppArmadillo.h>
#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <map>

// #include <RcppClock.h>

typedef std::map<std::pair<std::string, int>, double> TimesMap;

// [[Rcpp::export]]
void test(Rcpp::CharacterVector tick_names,
          Rcpp::CharacterVector tock_names,
          arma::vec tick_times,
          arma::vec tock_times)
{

    std::pair<TimesMap::iterator, bool> insertTime;
    std::pair<std::string, int> key;

    /* Sort ticks and tocks by tick_name and tock_name */

    TimesMap tickmap;
    for (std::size_t i = 0; i < tick_names.size(); ++i)
    {
        key.first = tick_names[i];
        key.second = i;
        insertTime = tickmap.insert(
            std::pair<std::pair<std::string, int>, double>(key, tick_times[i]));
    }

    TimesMap tockmap;
    for (std::size_t i = 0; i < tock_names.size(); ++i)
    {
        key.first = tock_names[i];
        key.second = i;
        insertTime = tockmap.insert(
            std::pair<std::pair<std::string, int>, double>(key, tock_times[i]));
    }
    std::cout << "\nTicks\n\n";
    for (auto const &time : tickmap)
    {
        std::cout << time.first.first << " | " << time.first.second << " | " << time.second << "\n";
    }

    std::cout << "\nTocks\n";
    for (auto const &time : tockmap)
    {
        std::cout << time.first.first << " | " << time.first.second << " | " << time.second << "\n";
    }
    std::cout << std::flush;
}
```

It's not finished but this code creates ordered maps for ticks and tocks. Consider this R example:
```
[R] tick_times <- c(1,3,6,10,11,16,20)                                                   
[R] tock_times <- c(3,11,10,12,18,25,26)                                                 
[R] tick_names <- c("A", "A", "B", "C", "C", "C", "D")                                   
[R] tock_names <- c("A", "C", "B", "C", "A", "C", "D")                                   
[R] test(tick_names, tock_names, tick_times, tock_times)                                 

Ticks

A | 0 | 1
A | 1 | 3
B | 2 | 6
C | 3 | 10
C | 4 | 11
C | 5 | 16
D | 6 | 20

Tocks
A | 0 | 3
A | 4 | 18
B | 2 | 10
C | 1 | 11
C | 3 | 12
C | 5 | 25
D | 6 | 26
```
Now that Ticks and Tocks are ordered we can easily calculate the tock-tick difference (or duration) and we are done.

This should be faster than making ticks*tocks comparisons and it should yield the exact same result.

**Comment by zdebruine** [comment]
Thanks for that!  Inspired by your perspective with `std::unordered_map` I was able to put together an even more efficient implementation.  Version 1.2 now contains that fix together with a few other minor enhancements, and a switch to `std::chrono::steady_clock` which surprisingly works better on my Windows machine than `std::chrono::high_resolution_clock`.  I'm going to test this on my Linux early next week at work, and if you can test everything on your mac and give a thumbs up that would be great.  Apparently `std::chrono::steady_clock` and `std::chrono::high_resolution_clock` can have OS-specific implementations, and different accuracy.

I've run a test similar to what you've done here:

```
//[[Rcpp::depends(RcppClock)]]
#include <RcppClock.h>

int fib(int n) {
  return ((n <= 1) ? n : fib(n - 1) + fib(n - 2));
}

// [[Rcpp::export]]
void fib_test(int n) {
  Rcpp::Clock clock;
  for (unsigned int x = 0; x < 50; ++x){
    clock.tick("outer loop");
    for (unsigned int y = 0; y < 50; ++y){
      clock.tick("inner loop");
      for (unsigned int z = 0; z < 50; ++z){
        clock.tick("function");
        fib(n);
        clock.tock("function");
      }
      clock.tock("inner loop");
    }
    clock.tock("outer loop");
  }
  clock.stop("times");
}
```

Everything runs within a second when I call the following from R:

```
fib_test(15)
times
```

**Comment by BerriJ** [comment]
This is fixed by https://github.com/zdebruine/RcppClock/commit/aa19372520dcc28125e3b6af01a0ada2aa4fa1d0
